version: 2
jobs:
  build:

    working_directory: ~/cassandra-sstable-generator

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - run: mvn install -Dversion.cassandra2=2.2.19 -Dversion.cassandra30=3.0.28 -Dversion.cassandra311=3.11.14 -Dversion.cassandra4=4.0.7 -Dversion.cassandra41=4.1.0

      - store_test_results:
          path: target/surefire-reports
