version: 2
jobs:
  build:

    working_directory: ~/cassandra-sstable-generator

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - run: mvn install

      - store_test_results:
          path: target/surefire-reports