version: 2
jobs:
  build:

    working_directory: ~/cassandra-sstable-generator

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - run: mvn install -Dversion.cassandra2=2.2.19 -Dversion.cassandra30=3.0.24 -Dversion.cassandra311=3.11.10 -Dversion.cassandra4=4.0-rc2

      - store_test_results:
          path: target/surefire-reports
